#import "lib.typ": conf, author
#import "@preview/colorful-boxes:1.3.1": colorbox
#show: doc => conf(
  title: "Functional Genomics Final",
  date: "October 21, 2024",
  authors: (
    author([David Lewis], email: "lewis3d7@mail.uc.edu"),
    author([Orry Willems], email: "willemoy@mail.uc.edu"),
    author([Joshua Zack], email: "zackjm@mail.uc.edu"),
    author([Jovitha Naidu], email: "naiduja@mail.uc.edu"),
    author([Zhaocheng Zhang], email: "zhang3zc@mail.uc.edu"),
  ),
  doc,
)
#let paper-name = [_Comprehensive Molecular Characterization of Clear Cell Renal Cell Carcinoma_]
#let iLNCS-data = "TCGA_KIRC_RNASeqV2_2019"
//#set par(
//  first-line-indent: 1em,
//  justify: true,
//)

= Background
Kidney cancer is one of the most common cancers worldwide with its subtype, clear cell renal cell carcinoma (ccRCC) forming 80% of the burden. @ClearCellRenal2020 Being overweight or obese and smoking tobacco are known risk factors for kidney cancer. Renal cancer risk is further increased by two additional factors, hypertension and acquired cystic kidney disease that necessitates dialysis. @kabariaRenalCellCarcinoma2016 Although the majority of renal carcinomas occur infrequently, 2–4% of occurrences are linked to inherited tumor syndromes, which each put people at risk for developing ccRCC. The most prevalent inherited tumor condition is von Hippel–Lindau (VHL) tumor syndrome of ccRCCs have somatic mutations or epigenetic changes in the VHL gene. @sanchezGeneticMetabolicHallmarks2018

One study @sceloVariationGenomicLandscape2014 explored the genomic landscape of clear cell renal cell carcinoma (ccRCC) across four European countries—Czech Republic, Romania, Russia, and the UK—using whole-genome sequencing and transcriptome analysis. It identified genetic alterations in pathways related to epigenetic regulation and PI3K/mTOR signaling, as well as novel pathways such as focal adhesion and extracellular matrix (ECM) components. The unusually high frequency of A:T4T:A transversions in Romanian patients, likely due to exposure to aristolochic acid, a known carcinogen, indicates potential geographic-specific mutational processes. Common mutations were found in genes such as VHL, PBRM1, SETD2, BAP1, and KDM5C which are involved in chromatin remodeling and cell signaling. These findings underscore the importance of including diverse populations in genomic studies to uncover specific mutational patterns, which may have implications for public health and therapeutic strategies for ccRCC.

These genes were also supported by findings from a recent study on the genomic landscape of ccRCC, @cottaCurrentLandscapeGenomic2023a which highlighted somatic mutations in genes such as VHL, PBRM1, SETD2, and BAP1, alongside copy number variations, multigene transcriptomic signatures, and distinct immune cell populations. Many of these biomarkers have been assessed for their correlation with survival, while a smaller subset has been explored as potential predictors of response to systemic therapy.

= Introduction
Here, we attempt to evaluate the paper, #paper-name @creightonComprehensiveMolecularCharacterization2013 using what should be the same datasets from the iLNCS @pilarczykConnectingOmicsSignatures2022 and cBioPortal @ceramiCBioCancerGenomics2012 genomics analysis platforms. #paper-name will be referred to as "the original paper" throughout this document.

#pagebreak()
= Clustering Analysis


#figure(
  image("heatmaps/kmeans_4_primary_solid_tumor-annotated.png"),
  caption: [k-means (1-Spearman): k=4 clustering],
) <cluster>


#figure(
  image("heatmaps/heatmap_from_paper.png"),
  caption: [Reference Heatmap from original paper],
)<cluster-reference>
The heatmaps depict expression levels in mRNA transcripts that are significantly up or down-regulated.
In the original paper, unsupervised clustering is performed using "consensus clustering"
@creightonComprehensiveMolecularCharacterization2013
which is an aggregation of several different clustering methods which are not disclosed. We were unable to replicate the results with any clustering method available through the Morpheus platform
@Morpheus using the iLNCS, #iLNCS-data, dataset. We settled on 1-Spearman correlation using the k-means clustering feature of Morpheus @Morpheus. While the clusters generated with Morpheus appear much noisier than the clusters from the original paper, there are still well-defined clusters. Cluster 2 is particularly well defined, showing a broad region of high expression. Each cluster may represent a potential putative subtype of clear cell renal cell carcinoma.

To match the original paper in any significant way, clusters were generated by first comparing "Primary Solid Tumor" and "Solid Tissue Normal" samples, thereby showing differential expression in the tumor groups. Then the "Solid Tissue Normal" samples were removed, leaving only the differential data for the "Primary Solid Tumor" group. Then unsupervised clustering was performed.

Performing unsupervised clustering without this selection resulted in results that were vastly different from the original paper and did not show differentiable clustering to anywhere near the same degree as in @cluster.

It should be noted that while the heatmap in @cluster does not use the "Subtract row mean, divide by standard deviation" feature of the Morpheus platform @Morpheus, the feature was tested and did not provide any significant visual difference to the heatmap in @cluster.

= Results
== Oncoprints

An "oncoprint" is a heatmap that visualizes genomic alterations; they are commonly used to assess the relationship between mutations in a particular molecular pathway or gene set. @CBioPortalFAQs Here, oncoprints are used to visualize the alterations in the top 9 mutated genes as given by cBioPortal as well as the set of genes in the PI3K pathway.

=== Oncoprints Using Top 9 Mutated Genes

An oncoprint for each of the clusters in @cluster are shown below. Each cluster appears to be a representative subset of the oncoprint in @oncoprint_custom_genes_all. VHL is the most altered gene in all clusters. However, the top altered gene aside from VHL is somewhat variable depending on the cluster. For example, MUC4 and PBRM1 tend to be the 3rd and 4th most altered genes. However, in cluster 3, there is much higher percent alteration for SETD2, an important tumor suppressor involved in mismatch repair. @SETD2HistonelysineNmethyltransferase

#figure(
  image("oncoprints/oncoprint_custom_genes_all.png"),
  caption: [Top 9 mutated genes for all clusters.],
) <oncoprint_custom_genes_all>


#figure(
  image("oncoprints/oncoprint_custom_genes_1.png"),
  caption: [Top 9 mutated genes for cluster 1.],
) <oncoprint_custom_genes_1>
Cluster 1 shows unusually high percent alterations for BAP1, which is associated with BAP1 tumor suppression syndrome. BAP1 is an important tumor suppressor. @BAP1TumorPredisposition
#figure(
  image("oncoprints/oncoprint_custom_genes_2.png"),
  caption: [Top 9 mutated genes for cluster 2.],
) <oncoprint_custom_genes_2>


#figure(
  image("oncoprints/oncoprint_custom_genes_3.png"),
  caption: [Top 9 mutated genes for cluster 3.],
) <oncoprint_custom_genes_3>

Cluster 3 shows increased alterations in SETD2. Cluster 3 also shows relatively high percentage of alterations for BAP1.

#figure(
  image("oncoprints/oncoprint_custom_genes_4.png"),
  caption: [Top 9 mutated genes for cluster 4.],
) <oncoprint_custom_genes_4>

Cluster 4 shows relatively high percent alterations for SETD2, but not for BAP1, differentiating cluster 4 from cluster 3.

#figure(
  image("oncoprints/oncoprint_from_paper_top_mutated_genes.png"),
  caption: [Reference "oncoprint" from paper showing mutation events. ],
) <reference_oncoprint_top_9>

Note that the set of genes given in @reference_oncoprint_top_9 is not consistent with the top 9 mutations given in @oncoprint_custom_genes_all; however, VHL, PBRM1, and SETD2 alterations are roughly consistent with the patterns in @reference_oncoprint_top_9.

=== Examining the PI3K Pathway
We generated oncoprints for each of the clusters using the same genes as the reference oncoprint in @oncoprint_from_paper from the original paper depicting the alterations in the genes related to the PI3K pathway. The PI3K pathway is an important pathway for the regulation of the cell cycle and is often activated in cancers. @heTargetingPI3KAkt2021

#figure(
  image("oncoprints/cluster-all-annotated.png"),
  caption: [Oncoprint representing samples from all clusters.],
) <oncoprint-all>

The oncoprint representing all the clusters for the PI3K pathway is almost identical to the one given in the original paper, shown in @oncoprint_from_paper. This is expected, as they use a similar dataset. @oncoprint_from_paper does have some differences, showing a category not present in the cBioPortal generated oncoprints, namely mRNA up-regulation. The mRNA category seems to be replaced with amplification and missense mutations in the cBioPortal generated oncoprints. This may be due to a limitation inherent in cBioPortal, or unstated differences in the datasets.




#figure(
  image("oncoprints/cluster1-annotated.png", width: 80%),
  caption: [Oncoprint representing samples from cluster 1.],
) <oncoprint-1>

The oncoprint for Cluster 1 is somewhat reminicient of the oncoprint in @oncoprint_from_paper, but the alterations tend to be reduced in number. This is expected if the alterations are common among clusters, i.e. the clusters are simply a reduced sample subset showing similar behavior.

#figure(
  image("oncoprints/cluster2-annotated.png"),
  caption: [Oncoprint representing samples from cluster 2],
) <oncoprint-2>
Out of all the clusters, Cluster 2 looks the most different when compared to @oncoprint_from_paper. This may mean that Cluster 2 is significantly different from the other putative subtypes (clusters) and may use a different pathway other than PI3K for tumorigenesis.

#figure(
  image("oncoprints/cluster3-annotated.png"),
  caption: [Oncoprint representing samples from cluster 3.],
) <oncoprint-3>

Cluster 3 is again reminiscent of @oncoprint_from_paper. @oncoprint-3 shows the reduced subset behavior seen in @oncoprint-1. Cluster 3 does appear to be the most representative of the total dataset.

#figure(
  image("oncoprints/cluster_4-annotated.png"),
  caption: [Oncoprint representing samples from cluster 4.],
) <oncoprint-4>

Cluster 4 again seems to be a small subset of the samples from @oncoprint_from_paper. Notably, it is missing any deep deletion alterations.

#figure(
  image("oncoprints/oncoprint_from_paper-annotated.png"),
  caption: [Reference oncoprint from the original paper.],
) <oncoprint_from_paper>

Overall, most of the clusters appear to be representative subsets of the overall dataset. Cluster 2 is an outlier in this regard, which may be due to significant differences compared to the other potential putative subtypes.

== Survival
Survival rates, both in total and over time are relatively consistent between clusters. Cluster 3 and 4 are notable exceptions, with cluster 3 having a much higher mortality rate and cluster 4 having a much lower rate of mortality. Notably, the KM plot for cluster 3 is also somewhat steeper, meaning that the mortality rate over time is also higher.


#let clusterstack(content, title: []) = stack(content, title)

#figure(
  stack(
    image("KM Plots/survivalstatus.svg", width: 80%),
    grid(
      columns: 5,
      clusterstack(image("KM Plots/KM Plot, only deceased - all clusters.png", width: 100%), title: "All Clusters"),
      clusterstack(image("KM Plots/KM Plot, only deceased - cluster 1.png", width: 100%), title: "Cluster 1"),
      clusterstack(image("KM Plots/KM Plot, only deceased - cluster 2.png", width: 100%), title: "Cluster 2"),
      clusterstack(image("KM Plots/KM Plot, only deceased - cluster 3.png", width: 100%), title: "Cluster 3"),
      clusterstack(image("KM Plots/KM Plot, only deceased - cluster 4.png", width: 100%), title: "Cluster 4"),
    ),
  ),
  caption: [
    The Bar chart represents the percentage of patients that did not survive the entire duration of data collection (5 years). The line plots show survivability over time (KM plot). Only the survivability for the patients that did not survive the duration of data collection is shown in the line plots.
  ],
)

= Methods

== Clustering methods

We used the “TCGA_KIRC_RNASeqV2_2019”, a 606-sample RNA-seq kidney renal
clear cell carcinoma dataset from iLINCS @pilarczykConnectingOmicsSignatures2022 as the primary dataset in this study.
In total, 19517 genes are in the dataset.
Because the reference mRNA clustering results to be compared in this study @creightonComprehensiveMolecularCharacterization2013
was generated by 500 representative genes, we
generated a signature with 508 genes by iLINCS
@pilarczykConnectingOmicsSignatures2022.

To generate the signature,
“sample_type” was chosen to be the grouping variable, with “Primary Solid Tumor” was
set as the treatment group and “Solid Tissue Normal” was set as the baseline group.
Next, we set the differential expression range as from -3.2 to 4.1, and selected 1e-10 as
the P-value cutoff. The distribution of selected 508 genes is shown in @volcano.

Then the 508-gene signature was transferred to Morpheus @Morpheus. Solid normal tissue
samples were removed before clustering, and 533 primary solid tumor samples were
subjected to Kmeans clustering. With knowledge from the reference mRNA clustering
@creightonComprehensiveMolecularCharacterization2013
, we chose 4 as the predefined number of clusters. Since extreme values were
shown in signature’s gene expression (@volcano), “1-spearman rank correlation” was
chosen as the metric for clustering to better handle outliers. Samples of each resulting
cluster were integrated with the “Kidney Renal Clear Cell Carcinoma (TCGA, Nature 2013)”
dataset on cBioPortal
@ceramiCBioCancerGenomics2012 @gaoIntegrativeAnalysisComplex2013
@debruijnAnalysisVisualizationLongitudinal2023
, for further gene alteration pattern investigations.

#figure(
  image(width: 60%, "supplemental-figures/volcano.png"),
  caption: [
    The volcano plot of 508 genes for signature generation. Selected genes are
    shown in green; genes below differential expression cutoff (-3.2 to 4.1) are shown in
    red; genes below differential expression cutoff and P-value cutoff (1e-10) are shown in
    black.],
) <volcano>
== Oncoprint Methods
Oncoprints were created using the cBioPortal platform by first converting the sample IDs from the iLNCS dataset into cBioPortal IDs using a Python script, then selecting those IDs using the cBioPortal web UI. Then genes of interest were selected for the oncoprint. In this way, oncoprints were created for each clustering for the PI3K pathway genes and the top 9 mutated genes for each cluster.

== Survival Methods
Survival plots were created using a mix of cBioPortal and the python programming language. Clusters were imported into cBioPortal from iLNCS in a similar way as in the oncoprint methods. The KM plots were created for the different clusters by downloading the KM plot from cBioPortal for each cluster after selecting the deceased patients. Percent deceased was also calculated from cBioPortal. These results were imported into python as plotted.



= Discussion

The results generally agree with the original paper. VHL, SETD2, and PBRM1 were found to be important drivers of clear cell renal cell carcinoma. However, the mRNA expression clusters depicted in @cluster-reference could not be reproduced using k-means clustering. This sheds doubt on the reliability of the molecular subtypes defined by the original paper. Other publications similarly do not agree on the number of molecular subtypes depending on clustering method. @brannonMolecularStratificationClear2010a

== Targeted Treatments

#underline[VHL] - Mutations in the VHL gene cause inappropriate activation of hypoxia-inducible factors (HIFs) that promote tumorigenesis through angiogenesis. A HIF inhibitor, Belzutifan (Hasanov, E., & Jonasch, E. (=2021). (MK-6482 as a potential treatment for von Hippel-Lindau disease-associated clear cell renal cell carcinoma. Expert Opinion on Investigational Drugs, 30(5), 495–504. https://doi.org/10.1080/13543784.2021.1925248), has been approved in 2021 as the first systemic treatment for adults with VHL disease (Narayan & Jonasch, 2022) (Narayan, V., & Jonasch, E. (2022). Systemic Therapy Development in Von Hippel–Lindau Disease: An Outsized Contribution from an Orphan Disease. Cancers, 14(21), 5313. https://doi.org/10.3390/cancers14215313)‌.

#underline[PBRM1] - Polybromo-1 (PBRM1) gene is associated with cell differentiation, cell proliferation and DNA repair. PBRM1 mutation is seen in 40% of ccRCC cases (Chabanon et al., 2021) (Chabanon, R. M., Morel, D., Eychenne, T., Colmet-Daage, L., Bajrami, I., Dorvault, N., Garrido, M., Meisenberg, C., Lamb, A., Ngo, C., Hopkins, S. R., Roumeliotis, T. I., Jouny, S., Hénon, C., Kawai-Kawachi, A., Astier, C., Konde, A., Del Nery, E., Massard, C., & Pettitt, S. J. (2021). PBRM1 Deficiency Confers Synthetic Lethality to DNA Repair Inhibitors in Cancer. Cancer Research, 81(11), 2888–2902. https://doi.org/10.1158/0008-5472.CAN-21-0628).
#let convertDataScript = read("convertData.py")

//#show figure: set block(breakable: true)
//#figure(
//raw(convertDataScript, lang: "python", block: true),
//caption: [Code that converts iLNCS IDs to cbioportal IDs]
//)
#bibliography(
  style: "american-medical-association",
  (
    // "bibliography/clustering.bib",
    // "bibliography/general.yaml",
    // "bibliography/background.bib",
    "bibliography/all.bib",
  ),
)

#pagebreak()
= Contributions to the Project
== David Lewis
Played the role of organizer, delegating tasks and guiding the analysis. Contributed to the clustering analysis section and oncoprint sections. Additionally, provided formatting for the document.

== Jovitha Naidu
Wrote and researched the background. Provided feedback for clustering. Provided biological insight for tissue categories (solid tissue normal).

== Orry Willems
Wrote script to convert iLNCS IDs into cBioPortal IDs facilitating oncoprint generationl. Also created oncoprints and provided descriptions for them.

== Joshua Zack
Created octoprints based on cluster groups. Wrote description for top 9 octoprint section. Provided feedback for clustering.


== Zhaocheng Zhang
Perform raw data processing and clustering analysis. Post-process clustering results for oncoprint comparisons. Write the clustering method section of report.