
main: 
	pandoc -i Homework_5_david_lewis.ipynb -o homework-5-david-lewis.pdf --pdf-engine=lualatex --variable documentclass=assignments  --variable title="Homework 5" --variable monofont=dejavusansmono -H packages.tex --variable author="David Lewis"

project: 
	pandoc -i data_science_project3_David_Lewis.ipynb -o data_science_project_3_david_lewis_M13335045.pdf --pdf-engine=lualatex --variable documentclass=assignments  --variable title="Project 3" --variable monofont=dejavusansmono -H packages.tex --variable author="David Lewis"
mo: 
	pandoc -i Khedekar_MNIST_CNN_HelloWorld_DLinColab.ipynb -o khedekar.pdf --pdf-engine=lualatex --variable documentclass=assignments  --variable title="Project 3" --variable monofont=dejavusansmono -H packages.tex --variable author="Mohini Khedekar"

moproject: 
	pandoc -i Khedekar_data_science_project3_NNclassifier.ipynb -o Khedekar_data_science_project3_NNclassifier.pdf --pdf-engine=lualatex --variable documentclass=assignments  --variable title="Project 3" --variable monofont=dejavusansmono -H packages.tex --variable author="Mohini Khedekar"