
main: 
	pandoc -i Homework_5_david_lewis.ipynb -o homework-5-david-lewis.pdf --pdf-engine=lualatex --variable documentclass=assignments  --variable title="Homework 5" --variable monofont=dejavusansmono -H packages.tex --variable author="David Lewis"